### ISSUE TITLE
What is the status of this fork?

### ISSUE THREAD

**Issue by demurgos** [uiri/toml-test#3]
Hi,
I came here from your [toml](https://github.com/uiri/toml) repository. This repo claims:

> The module passes [the TOML test suite](https://github.com/uiri/toml-test) which is a fork of [BurntSushi's TOML test suite](https://github.com/BurntSushi/toml-test).

This worries me: why can't there be a single test repo?
And more importantly: **does it mean there are incompatibilities?**

Is this fork competing with the base repo? Isn't it possible to merge the changes back to the main repo? I didn't see any PRs from this repo to the other.

Since this fork is not just temporary (because it is advertised on your toml project), I'd prefer if there was at least a section at the top of the README explaining why you keep a long lived-fork and what are the main differences/incompatibilites.
It would greatly help to assess the situation when looking for an interoperable format.

/cc @uiri

**Comment by uiri** [comment]
Hi Charles,

For my toml library, this repo is the single test repo. There are no incompatibilities with the main repo (that I recall). This repo exists solely to merge in additional tests which I want to use for my toml library that have not yet been merged in the main repo. I link to this repo rather than the main repo so that contributors to my toml library know that there are additional tests that they need to run their changes against.

Actually, I *do* view this fork as temporary. Alas, there is nothing quite so permanent as a temporary solution so this fork has lived for quite a bit longer than I would have liked when I initially created it. It should be very easy to merge this repo back into the main one.

@BurntSushi could you please comment on the current status of the main toml-test repo? If you no longer wish to maintain it, I would be willing to step in as I am still using it.

**Comment by demurgos** [comment]
Thanks for the reply.
It's good to know that you are careful about not fracturing the ecosystem.

Given your work on the Python lib, I would also consider that the best outcome would be to merge your changes of even grant you write access to the base repo.

If it's not possible, could you add your comment above somewhere in the README? It's a good reply.

**Comment by BurntSushi** [comment]
I don't see myself maintaining `toml-test` any time in the near future. @uiri How do you want to handle this? I'd be willing to transfer ownership to you or just add you as a contributor to the repo where it is now.

IIRC, there was at one point a plan to move it to the TOML organization itself, so it might be good to keep that in mind for the future.

**Comment by uiri** [comment]
Just adding me as a contributor to the repo where it is now will be less complicated. I don't think transfers work when the transferee already has a fork.

I will keep that plan in mind for the future :)

**Comment by BurntSushi** [comment]
@uiri Done! Thanks. :-)

**Comment by demurgos** [comment]
Closing this issue now that you have access to the main repo. Thank you all.
